FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
     libgl1 \
     libglib2.0-0 \
     && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    numpy==1.26.4 \
    opencv-python-headless==4.9.0.80 \
    Pillow==10.2.0 \
    torch==2.6.0 \
    torchvision==0.21.0 \
    ultralytics==8.1.0

COPY norgesgruppen/submissions /app/submissions

ENTRYPOINT ["python"]
